import type { Metadata } from 'next';
import { poppins } from './components/fonts';
import './globals.css';
import ThemeProvider from './components/context';

export const metadata: Metadata = {
  title: "Kha's Portfolio",
  description: 'Generated by create next app',
  icons: {
    icon: {
      url: '/logo/logo-dark.png',
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      {/* <body className={`${poppins.className} antialiased`}>{children}</body>; */}
      <body className={`${poppins.className} antialiased`}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
